
import { Language, Translation, Candidate, NewsItem, RankInfo } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  zh: {
    navHome: "首页",
    navAbout: "项目理念",
    navCandidates: "媒体英雄",
    navVoting: "共治投票",
    navRelax: "真相实验室",
    connectWallet: "绑定身份",
    heroTitle: "真相之火，永不熄灭",
    heroSub: "在谎言的深渊中，我们是唯一的灯塔。利用分布式技术与 AI，打破信息的铁幕。",
    heroBadge: "打破沉默的枷锁",
    heroCtaVote: "参与年度投票",
    heroCtaLab: "进入实验室",
    heroQuote: "“如果真相被封锁，这里就是它的避风港。”",
    heroQuoteSub: "智安协议：每一份真相，都值得被世界听见",
    statCensorshipTitle: "被抹除的记忆",
    statCensorshipValue: "32 亿",
    statCensorshipUnit: "人次",
    statCensorshipDesc: "在全球近 40% 的地区，真相是被包装的谎言。人们正因信息匮乏而失去对未来的选择权。",
    statCensorshipSource: "源自：UNESCO & RSF 实时统计",
    statJournalistTitle: "暗夜持灯者",
    statJournalistValue: "1,204",
    statJournalistUnit: "名",
    statJournalistDesc: "去年，超过千名媒体人因揭露真相而牺牲。他们的名字不应被风化，而应在网络中永生。",
    statJournalistSource: "由智安协议 (ZHIAN) 加密保存",
    aboutTitle: "智安宣言：为自由而生",
    aboutSub: "我们不仅是一个项目，更是一场关于真相的分布式革命。",
    missionTitle: "核心使命",
    missionDesc: "在算法与权力的夹缝中，构建永不落幕的真相博物馆。让勇气不再昂贵，让事实回归本质。",
    tokenModelTitle: "ZA 治理模型",
    tokenDistTitle: "自由配额",
    tokenRewardTitle: "英雄奖励",
    tokenRewardDesc: "ZA 代币是您参与治理、捍卫真相的选票。每年 10% 流通代币将奖给敢于发声的人。",
    tokenComplianceTitle: "合规说明",
    tokenComplianceDesc: "本平台目前仅用于社会学实验与演示。不涉及非法融资，旨在探索新闻自由的新边界。",
    legalDisclaimerTitle: "法律免责",
    legalDisclaimerDesc: "ZHIAN 坚持全球公益性质。所有档案均经过多方节点验证，我们对事实本身保持敬畏。",
    candidateTitle: "真相守望者",
    candidateSub: "这是属于那些不屈灵魂的丰碑。点击档案，感受他们曾经历的暗流与荣光。",
    candidateBadge: "全球英雄档案库",
    viewDetails: "查阅档案",
    voteBtn: "致敬英雄",
    archiveTitle: "真相存证系统",
    archiveVerified: "记录已上链，不可篡改",
    closeArchive: "退出档案",
    votingTitle: "共治真相",
    votingSub: "只有真正关心未来的人，才拥有投票的权力。",
    votingThreshold: "门槛：ZA 持有量",
    votingPurpose: "治理初衷",
    votingPurposeDesc: "我们希望通过投票，让那些被主流媒体遗忘、但在局部冲突中坚守真相的英雄得到资助。",
    votingStatus: "治理状态",
    votingWalletStatus: "未检测到身份凭证，请先绑定钱包。",
    votingPower: "ZA 治理积分",
    votingQualified: "您已获得真相投票权",
    votingInsufficient: "ZA 积分不足 (需 500 ZA)",
    votingAction: "前往英雄榜发声",
    labTitle: "真相实验室",
    labSub: "在被重构的现实中，训练你洞察谎言的双眼。",
    labBack: "返回大厅",
    gameVerifierTitle: "逻辑拆解",
    gameVerifierDesc: "撕开精心编排的叙事，识别权威背后的逻辑陷阱。",
    gameTrapsTitle: "情绪陷阱",
    gameTrapsDesc: "判断标题是在描述事实，还是在煽动你的肾上腺素。",
    gameManipulationTitle: "真相还原",
    gameManipulationDesc: "模拟新闻审查：从涂黑的段落中，推理出被隐藏的关键证据。",
    gameCorrect: "洞察如炬！",
    gameWrong: "信号受到干扰...",
    gameNext: "下一挑战",
    gameFinish: "训练达成",
    gameRestart: "再次挑战",
    gameStreak: "连胜",
    gameRank: "当前段位",
    gameAiGenerating: "正在同步全球真相态势...",
    footerQuote: "“真相可能被暂时扼杀，但真相的种子在分布式网络中永生。”",
    footerContact: "投稿与合作",
    footerArchive: "档案全集",
    footerGovernance: "治理委员会"
  },
  en: {
    navHome: "Home",
    navAbout: "Manifesto",
    navCandidates: "Heroes",
    navVoting: "Consensus",
    navRelax: "Truth Lab",
    connectWallet: "Connect Wallet",
    heroTitle: "FIRE OF TRUTH NEVER DIES",
    heroSub: "In the abyss of deception, we are the lighthouse. Breaking curtains with technology.",
    heroBadge: "BREAKING THE CHAINS",
    heroCtaVote: "Annual Vote",
    heroCtaLab: "Enter Lab",
    heroQuote: "“If truth is blocked, this is its safe harbor.”",
    heroQuoteSub: "ZHIAN: Every truth deserves to be heard.",
    statCensorshipTitle: "Redacted Memories",
    statCensorshipValue: "3.2 B",
    statCensorshipUnit: " People",
    statCensorshipDesc: "In 40% of the world, truth is a packaged lie. People are losing their choice of future.",
    statCensorshipSource: "Source: UNESCO & RSF Live Stats",
    statJournalistTitle: "Torch Bearers",
    statJournalistValue: "1,204",
    statJournalistUnit: "Persons",
    statJournalistDesc: "Over 1,000 fallen heroes last year. Their names live forever in our network.",
    statJournalistSource: "Preserved by ZHIAN Protocol",
    aboutTitle: "The Manifesto",
    aboutSub: "Not just a project, but a decentralized revolution.",
    missionTitle: "Core Mission",
    missionDesc: "Building an immutable museum of truth. Making courage affordable and facts essential.",
    tokenModelTitle: "ZA Governance",
    tokenDistTitle: "Distribution",
    tokenRewardTitle: "Incentives",
    tokenRewardDesc: "ZA tokens are your votes. 10% rewarded to those who dare to speak out.",
    tokenComplianceTitle: "Compliance",
    tokenComplianceDesc: "Social experiment for demo. Exploring new frontiers of press freedom.",
    legalDisclaimerTitle: "Disclaimer",
    legalDisclaimerDesc: "ZHIAN is non-profit. Records verified across nodes with reverence for facts.",
    candidateTitle: "Watchers",
    candidateSub: "A monument for unyielding souls. Explore their archives.",
    candidateBadge: "Global Archives",
    viewDetails: "View Archive",
    voteBtn: "Vote Respect",
    archiveTitle: "Truth Storage",
    archiveVerified: "Immutable Record",
    closeArchive: "Close Archive",
    votingTitle: "Joint Consensus",
    votingSub: "Only those who care have the power to vote.",
    votingThreshold: "Threshold: ZA Balance",
    votingPurpose: "Intent",
    votingPurposeDesc: "Funding heroes overlooked by mainstream media in regional conflicts.",
    votingStatus: "Live Status",
    votingWalletStatus: "No wallet detected. Connect first.",
    votingPower: "Governance Power",
    votingQualified: "You can vote",
    votingInsufficient: "Insufficient ZA (500 req)",
    votingAction: "Vote Now",
    labTitle: "Truth Lab",
    labSub: "Train your eyes to pierce deception.",
    labBack: "Exit Lab",
    gameVerifierTitle: "Logic Decoder",
    gameVerifierDesc: "Identify traps behind crafted narratives.",
    gameTrapsTitle: "Emotional Bait",
    gameTrapsDesc: "Is it fact or adrenaline manipulation?",
    gameManipulationTitle: "Restoration",
    gameManipulationDesc: "Deduce evidence from redacted snippets.",
    gameCorrect: "Insightful!",
    gameWrong: "Signal Lost...",
    gameNext: "Next Challenge",
    gameFinish: "Lab Cleared",
    gameRestart: "Retry",
    gameStreak: "Streak",
    gameRank: "Rank",
    gameAiGenerating: "Synchronizing global landscape...",
    footerQuote: "“Truth may be killed temporarily, but its seeds live forever.”",
    footerContact: "Contact",
    footerArchive: "Archives",
    footerGovernance: "Council"
  }
};

export const RANKS: Record<number, RankInfo> = {
  0: { name: "见习 (Intern)", color: "text-slate-400", bgColor: "bg-slate-100", shadowColor: "shadow-slate-200" },
  10: { name: "初级 (Junior)", color: "text-blue-500", bgColor: "bg-blue-100", shadowColor: "shadow-blue-200" },
  20: { name: "记者 (Reporter)", color: "text-indigo-600", bgColor: "bg-indigo-100", shadowColor: "shadow-indigo-300" },
  40: { name: "资深 (Senior)", color: "text-emerald-600", bgColor: "bg-emerald-100", shadowColor: "shadow-emerald-300" },
  60: { name: "首席 (Chief)", color: "text-purple-600", bgColor: "bg-purple-100", shadowColor: "shadow-purple-400" },
  80: { name: "传奇 (Legend)", color: "text-amber-600", bgColor: "bg-amber-100", shadowColor: "shadow-amber-400" },
  100: { name: "持灯者 (Guardian)", color: "text-red-600", bgColor: "bg-red-100", shadowColor: "shadow-red-500" }
};

export const RUNNER_OBSTACLES = {
  zh: {
    top: ["领导施压", "撤稿指令", "利益交换", "虚假通稿", "流量陷阱"],
    bottom: ["死亡威胁", "法律恐吓", "暴力袭击", "造谣抹黑", "账户封禁"]
  },
  en: {
    top: ["Editor Pressure", "Kill Order", "Conflict of Interest", "Fake Release", "Traffic Trap"],
    bottom: ["Death Threat", "Legal Trap", "Physical Assault", "Defamation", "Account Ban"]
  }
};

export const BRAND_LOGO_PROMPT = "Ultra-high resolution minimalist vector logo. A white peace dove snapping heavy metallic chains. Minimalist aesthetic, sapphire blue and silver palette, solid white background.";
export const HERO_GENERATION_PROMPT = (lang: string) => `Generate 20 investigative journalist profiles. Language: ${lang}. Output JSON only.`;
export const LOGO_CACHE_KEY = 'zhian_logo_v3';
export const HEROES_CACHE_KEY = 'zhian_heroes_v2';

export const getMockNews = (lang: Language): NewsItem[] => [
  { 
    id: 1, 
    title: lang === 'zh' ? "官方称由于‘技术故障’封锁社交媒体。" : "Official claims social media blocked due to 'Glitch'.", 
    isTrue: false, 
    explanation: lang === 'zh' ? "此类手段常用于压制现场实时信息。" : "Commonly used to suppress live info." 
  },
  { 
    id: 2, 
    title: lang === 'zh' ? "过去10年，全球超过800名记者殉职。" : "Over 800 journalists killed in last decade.", 
    isTrue: true, 
    explanation: "Data from UNESCO confirms this." 
  }
];
