
import { Language, Translation, Candidate, NewsItem } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  zh: {
    navHome: "首页",
    navAbout: "项目理念",
    navCandidates: "媒体人英雄",
    navVoting: "共治投票",
    navRelax: "真相实验室",
    connectWallet: "绑定身份",
    heroTitle: "智安：守护全球新闻自由",
    heroSub: "打破高墙，让真相之光照亮被掩盖的角落。",
    heroBadge: "打破沉默的枷锁",
    heroCtaVote: "参与年度投票",
    heroCtaLab: "进入实验室",
    heroQuote: "“如果真相被封锁，这里就是它的避风港。”",
    heroQuoteSub: "利用分布式技术，确保每一份真相都能冲破枷锁",
    statCensorshipTitle: "真相被拦截",
    statCensorshipValue: "32 亿",
    statCensorshipUnit: "人次",
    statCensorshipDesc: "全球近 40% 的人口生活在新闻自由受限的环境下。他们正在因无法获取真实的医疗、社会及法律信息而遭受系统性迫害。",
    statCensorshipSource: "数据源：UNESCO & RSF 实时统计",
    statJournalistTitle: "牺牲的守望者",
    statJournalistValue: "1,204",
    statJournalistUnit: "名",
    statJournalistDesc: "这是去年因进行独立调查而遭到谋杀、非法拘禁或“被消失”的英雄人数。每一笔记录，都是在用血肉之躯挑战铁幕。",
    statJournalistSource: "智安协议已加密保存其调查档案",
    aboutTitle: "项目蓝图与白皮书",
    aboutSub: "为了一个更透明、更自由的全球媒体环境。",
    missionTitle: "使命",
    missionDesc: "在当前全球新闻自由面临诸多挑战的背景下，智安 (ZHIAN) 坚信技术创新可以为媒体生态创造新的机遇。我们通过建立一套去中心化的声誉评价体系，奖励那些为揭露社会不公、捍卫真相而做出卓越贡献的媒体人。",
    tokenModelTitle: "ZhanCoin (ZA) 经济模型",
    tokenDistTitle: "代币分配",
    tokenRewardTitle: "奖励机制",
    tokenRewardDesc: "每年，社区用户通过投票选出表现卓越的媒体英雄。得票数排名靠前的个人或机构将分享该年度解锁的 10% ZA 代币。7 年分发结束后，我们将使用网站部分收益进行代币回购。",
    tokenComplianceTitle: "合规特别说明",
    tokenComplianceDesc: "ZA Coin 现阶段仅作为演示凭证使用。项目目前不接受任何形式的投资建议，也不直接挂钩法币资产。我们的目标是建立一种象征勇气 and 透明度的荣誉勋章，而非投机性金融工具。",
    legalDisclaimerTitle: "法律免责声明",
    legalDisclaimerDesc: "ZHIAN 致力于全球公益事业。网站所展示的媒体人案例仅代表其个人职业成就。我们不涉及任何证券发行、法币交易。用户参与投票即表示认同本项目公益性质。",
    candidateTitle: "媒体人英雄",
    candidateSub: "记录那些用生命与尊严换取真相的灵魂。他们的档案已通过 Web3 永久存证。",
    candidateBadge: "全球真相捍卫者",
    viewDetails: "查阅档案",
    voteBtn: "致敬并支持",
    archiveTitle: "智安真相档案",
    archiveVerified: "档案已验证",
    closeArchive: "关闭档案",
    votingTitle: "共治投票",
    votingSub: "只有持有 ZA 代币的参与者才能投票，确保社区治理的高质量。",
    votingThreshold: "投票门槛",
    votingPurpose: "机制目的",
    votingPurposeDesc: "我们旨在通过这一过程，从草根阶层发现那些未被主流媒体报道、却在地方性真相揭露中发挥关键作用的英雄。",
    votingStatus: "当前治理状态",
    votingWalletStatus: "您尚未连接钱包，无法验证治理权重。",
    votingPower: "ZA 治理积分",
    votingQualified: "您已获得投票资格",
    votingInsufficient: "余额不足：投票需 500 ZA",
    votingAction: "立即前往英雄榜单投票",
    labTitle: "真相实验室",
    labSub: "这里是每一位真相捍卫者的训练营。通过互动实验，识破隐形的高墙与操纵。",
    labBack: "返回实验室首页",
    gameVerifierTitle: "真假实验室",
    gameVerifierDesc: "你能从精心编织的叙事中，识别出哪些事实正在被掩盖吗？",
    gameTrapsTitle: "标题党陷阱",
    gameTrapsDesc: "“震惊”背后往往是逻辑的断层。学习识破那些武器化的语言诱导。",
    gameManipulationTitle: "一剪定乾坤",
    gameManipulationDesc: "删掉一句话，事实就会反转。体验“选择性呈现”对大众认知的操控力量。",
    gameCorrect: "洞察敏锐！",
    gameWrong: "不幸被误导...",
    gameNext: "继续前进",
    gameFinish: "测试完成",
    gameRestart: "重新挑战",
    footerQuote: "“真相可能被扼杀，但真相的种子在分布式网络中永生。”",
    footerContact: "投票及投稿联系",
    footerArchive: "档案库",
    footerGovernance: "治理"
  },
  en: {
    navHome: "Home",
    navAbout: "Initiative",
    navCandidates: "Heroes",
    navVoting: "Voting",
    navRelax: "Truth Lab",
    connectWallet: "Connect ID",
    heroTitle: "ZHIAN: Guarding Global Press Freedom",
    heroSub: "Breaking walls, letting the light of truth shine on hidden corners.",
    heroBadge: "BREAKING THE CHAINS OF SILENCE",
    heroCtaVote: "Join Annual Voting",
    heroCtaLab: "Enter Truth Lab",
    heroQuote: "“If truth is blocked, this is its safe harbor.”",
    heroQuoteSub: "Ensuring every piece of truth breaks through using decentralized tech.",
    statCensorshipTitle: "Truth Intercepted",
    statCensorshipValue: "3.2 Billion",
    statCensorshipUnit: "People",
    statCensorshipDesc: "Nearly 40% of the global population lives under restricted press freedom, suffering from systematic suppression of information.",
    statCensorshipSource: "Source: UNESCO & RSF Live Statistics",
    statJournalistTitle: "Fallen Guardians",
    statJournalistValue: "1,204",
    statJournalistUnit: "Persons",
    statJournalistDesc: "Number of heroes murdered, detained, or 'disappeared' last year for independent investigations. Every record is a testament to courage.",
    statJournalistSource: "Encrypted Archives preserved by ZHIAN Protocol",
    aboutTitle: "Blueprint & Whitepaper",
    aboutSub: "For a more transparent and free global media ecosystem.",
    missionTitle: "Mission",
    missionDesc: "ZHIAN believes technological innovation creates new opportunities for press freedom. We reward those exposing social injustice through a decentralized reputation system.",
    tokenModelTitle: "ZhanCoin (ZA) Economic Model",
    tokenDistTitle: "Token Distribution",
    tokenRewardTitle: "Reward Mechanism",
    tokenRewardDesc: "The community votes for media heroes annually. Top candidates share 10% of unlocked ZA. ZHIAN will use profits for buybacks after 7 years.",
    tokenComplianceTitle: "Compliance Notice",
    tokenComplianceDesc: "ZA Coin is currently for demo purposes only. We do not provide financial advice or link to fiat. It is a badge of honor, not a speculative tool.",
    legalDisclaimerTitle: "Legal Disclaimer",
    legalDisclaimerDesc: "ZHIAN is a non-profit initiative. Cases shown represent individual achievements. We do not issue securities or trade fiat assets.",
    candidateTitle: "Media Heroes",
    candidateSub: "Recording souls who traded life for truth. Their archives are permanently stored on Web3.",
    candidateBadge: "Global Truth Guardians",
    viewDetails: "View Archives",
    voteBtn: "Support",
    archiveTitle: "ZHIAN Truth Archives",
    archiveVerified: "Archive Verified",
    closeArchive: "Close Archive",
    votingTitle: "Governance Voting",
    votingSub: "Only ZA holders can vote to ensure high-quality community governance.",
    votingThreshold: "Threshold",
    votingPurpose: "Purpose",
    votingPurposeDesc: "We aim to discover grassroots heroes who play key roles in local truth-telling but are overlooked by mainstream media.",
    votingStatus: "Governance Status",
    votingWalletStatus: "Wallet not connected. Connect to verify governance weight.",
    votingPower: "ZA Governance Points",
    votingQualified: "You are qualified to vote",
    votingInsufficient: "Insufficient Balance: 500 ZA required",
    votingAction: "Proceed to Vote",
    labTitle: "Truth Lab",
    labSub: "The training ground for truth seekers. Identify invisible walls and manipulations.",
    labBack: "Back to Lab Home",
    gameVerifierTitle: "Verifier Lab",
    gameVerifierDesc: "Can you identify which facts are being hidden from carefully woven narratives?",
    gameTrapsTitle: "Clickbait Traps",
    gameTrapsDesc: "Behind 'Shocking' headlines are often logical gaps. Learn to spot weaponized language.",
    gameManipulationTitle: "The Power of Redaction",
    gameManipulationDesc: "Delete one sentence, and the truth flips. Experience the power of selective presentation.",
    gameCorrect: "Sharp Insight!",
    gameWrong: "Misled by noise...",
    gameNext: "Move Forward",
    gameFinish: "Test Complete",
    gameRestart: "Try Again",
    footerQuote: "“Truth may be killed, but its seeds live forever in decentralized networks.”",
    footerContact: "Voting & Submission Contact",
    footerArchive: "Archives",
    footerGovernance: "Governance"
  }
};

export const getMockCandidates = (lang: Language): Candidate[] => [
  {
    id: 1,
    name: lang === 'zh' ? "达芙妮·卡鲁阿纳·加利齐亚" : "Daphne Caruana Galizia",
    region: lang === 'zh' ? "马耳他" : "Malta",
    bio: lang === 'zh' 
      ? "揭露了马耳他政界与巴拿马文件相关的腐败。她的笔触直达国家最黑暗的角落。" 
      : "Exposed corruption in Malta related to the Panama Papers. Her pen reached the nation's darkest corners.",
    achievement: lang === 'zh' 
      ? "揭露了地中海岛国深层政府与跨国洗钱的利益链条。" 
      : "Exposed deep-state laundering chains in the Mediterranean.",
    votes: 4520,
    imageUrl: "https://images.unsplash.com/photo-1585829365234-758999120619?q=80&w=1000&auto=format&fit=crop",
    publishDate: "2017-10-16",
    sourceType: lang === 'zh' ? "腐败调查" : "Corruption Investigation",
    fullArchive: lang === 'zh' ? "### 档案：地中海的暗流..." : "### Archive: Mediterranean Undercurrents..."
  },
  {
    id: 2,
    name: "Maria Ressa",
    region: lang === 'zh' ? "菲律宾" : "Philippines",
    bio: lang === 'zh' 
      ? "Rappler 创始人，诺贝尔和平奖得主。她坚守调查前线。" 
      : "Founder of Rappler, Nobel Peace Prize laureate. She stands on the front line of investigation.",
    achievement: lang === 'zh' 
      ? "揭露了社交媒体被武器化以操纵民众的真相。" 
      : "Exposed the weaponization of social media for public manipulation.",
    votes: 3890,
    imageUrl: "https://images.unsplash.com/photo-1544717297-fa95b3ee51f8?q=80&w=1000&auto=format&fit=crop",
    publishDate: "2021-12-10",
    sourceType: "Human Rights",
    fullArchive: "### Archive: Algorithms & Bullets..."
  }
];

export const getMockNews = (lang: Language): NewsItem[] => [
  { 
    id: 1, 
    title: lang === 'zh' ? "官方称由于‘技术故障’暂时封锁社交媒体。" : "Official claims social media blocked due to 'Technical Glitch'.", 
    isTrue: false, 
    explanation: lang === 'zh' ? "历史证明，这种封锁通常是为了压制现场信息。" : "History proves such blocks usually suppress live events." 
  },
  { 
    id: 2, 
    title: lang === 'zh' ? "过去10年，全球超过800名记者牺牲。" : "Over 800 journalists killed globally in the last decade.", 
    isTrue: true, 
    explanation: "According to UNESCO data." 
  }
];

// Use the data URL for the uploaded image representing the bird breaking chains over a book
export const LOGO_SRC = "https://r.jina.ai/i/06093259e0f64c63955d9d97a92289c0";
